# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestProcurandoNotebookNitro5():
    
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def test_procurandonotebooknitro5(self):
        self.driver.get("https://www.magazineluiza.com.br/")
        self.driver.maximize_window()
        self.driver.find_element(By.ID, "input-search").click()
        self.driver.find_element(By.ID, "input-search").send_keys("acer nitro 5")
        self.driver.find_element(By.CSS_SELECTOR, ".dQJKma").click()
        
        element = self.driver.find_element(By.LINK_TEXT, "Guia de segurança")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "select-desktop-with-label").click()
        dropdown = self.driver.find_element(By.ID, "select-desktop-with-label")
        dropdown.find_element(By.XPATH, "//option[. = 'Menor Preço']").click()

    def teardown_method(self):
        self.driver.quit()
        
if __name__ == "__main__":
    teste = TestProcurandoNotebookNitro5()
    teste.setup_method()
    teste.test_procurandonotebooknitro5()
    teste.teardown_method()